server:
  port: 9992
  servlet:
    context-path: /auth
    session:
      timeout: 60
  use-forward-headers: true

spring:
  profiles:
    active: dev
  application:
    name: unicome-oauth
  mvc:
    static-path-pattern: /public/**
  messages:
    basename: i18n/messages
    cache-duration: 3600
    encoding: UTF-8
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5


#  cache:
#    type: ehcache
#    ehcache:
#      config: classpath:profiles/ehcache.xml

#eureka:
#  instance:
##    prefer-ip-address: true
#    hostname: localhost
#    port: 8761
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
##    register-with-eureka: true # 向服务中心注册自己
##    fetch-registry: true # 检索服务


security:
  basic:
    enabled: false # 关闭http basic认证
#  sso: #  sso单点登陆
#    loginPath: /login
  ignored: /css/**,/js/**,/favicon.ico,/webjars/**

logging:
  level.org.springframework.security: DEBUG
  level.org.springframework.data.mongodb.core: DEBUG