server:
  servlet:
    context-path: /auth
    session:
      timeout: 1800
  use-forward-headers: true

# spring
spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  messages:
    basename: i18n/messages
    cache-duration: 3600
    encoding: UTF-8
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5


#  cache:
#    type: ehcache
#    ehcache:
#      config: classpath:profiles/ehcache.xml

eureka:
  instance: # 当前Eureka Instance实例配置信息
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    hostname: localhost # 服务注册中心实例的主机名
  client: # 客户端配置
    register-with-eureka: true # 是否向服务注册中心注册自己，单机设置为false，集群设置为true
    fetch-registry: true # 是否检索服务，服务注册中心维护实例，不需要去检索其他服务
    service-url.defaultZone: http://localhost:8761/eureka/eureka

security:
  basic:
    enabled: false # 关闭http basic认证
  ignored: /favicon.ico,/js/**,/css/**,/webjars/**
  oauth2:
    client:
      client-id: client1
      client-secret: secret1
      scope: app
      access-token-uri: http://localhost:9992/auth/oauth/token
      user-authorization-uri: http://localhost:9992/auth/oauth/authorize
logging:
  level.org.springframework.security: DEBUG
  level.org.springframework.data.mongodb.core: DEBUG

encrypt:
  key-store:
    alias: mytest
    location: mytest.jks
    secret: mypass

info: # actuator
  app.name: ${spring.application.name}
  company.name: www.unicome.org
  build:
    groupId: "@project.groupId@"
    artifactId: "@project.artifactId@"
    version: "@project.version@"