spring:
    application.name: unicome-basic
    cloud.config:
        profile: dev
        label: dev
        uri:
    jpa.show-sql: true
    # mongodb
#    data:
#        mongodb:
#            uri: mongodb://127.0.0.1:27017/unicome_basic
    # mysql
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/unicome_basic
        username: root
        password: 123456

logging.level:
    org.springframework.cloud: DEBUG