server:
  port: 8888
  servlet:
    context-path: /cms
  use-forward-headers: true
spring:
  application:
    name: unicome-cms
  data:
    mongodb:
      uri: mongodb://52.69.9.211:27017/unicome_cms2