server:
    port: 9500
    servlet-context: /mq

spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
#        address: amqp://guest:guest@localhost